Plug 'tpope/vim-fugitive'
Plug 'scrooloose/nerdtree'
Plug 'vim-scripts/Tagbar'
Plug 'altercation/vim-colors-solarized' 
Plug 'rakr/vim-one' 
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes' 
Plug 'airblade/vim-gitgutter' 
Plug 'jlanzarotta/bufexplorer'
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim' 
Plug 'junegunn/goyo.vim'
Plug 'rafi/awesome-vim-colorschemes'
Plug 'terryma/vim-smooth-scroll'
